version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        update-types:
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        update-types:
          - "patch"
  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    groups:
      docker-patch-updates:
        update-types:
          - "patch"
  - package-ecosystem: "docker-compose"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    groups:
      docker-compose-patch-updates:
        update-types:
          - "patch"
