FROM golang:1.24.3@sha256:86b4cff66e04d41821a17cea30c1031ed53e2635e2be99ae0b4a7d69336b5063 AS build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
# cgo needed for go-sqlite3
RUN CGO_ENABLED=1 go build -v -o ./witness-add-key ./cmd/witness-add-key

FROM golang:1.24.3@sha256:86b4cff66e04d41821a17cea30c1031ed53e2635e2be99ae0b4a7d69336b5063

WORKDIR /home/app

RUN apt-get update
RUN apt-get install sqlite3

RUN mkdir witness
RUN sqlite3 -line witness/witness.db '.database'

COPY --from=build /build/witness-add-key ./

ENTRYPOINT ["./witness-add-key"]
CMD ["--database-path=/home/app/witness/witness.db", "--public-key=/home/app/keys/public.key"]
