FROM golang:1.25.1@sha256:a5e935dbd8bc3a5ea24388e376388c9a69b40628b6788a81658a801abbec8f2e AS build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN CGO_ENABLED=0 go build -v -o ./gen-key ./cmd/gen-key

FROM golang:1.25.1@sha256:a5e935dbd8bc3a5ea24388e376388c9a69b40628b6788a81658a801abbec8f2e 

WORKDIR /home/app

COPY --from=build /build/gen-key ./

ENTRYPOINT ["./gen-key"]
CMD ["--origin=binarytransparency.log/example", "--private-key-path=/home/app/keys/private.key", "--public-key-path=/home/app/keys/public.key"]
