FROM golang:1.24.4@sha256:10c131810f80a4802c49cab0961bbe18a16f4bb2fb99ef16deaa23e4246fc817 AS build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN CGO_ENABLED=0 go build -v -o ./gen-key ./cmd/gen-key

FROM golang:1.24.4@sha256:10c131810f80a4802c49cab0961bbe18a16f4bb2fb99ef16deaa23e4246fc817 

WORKDIR /home/app

COPY --from=build /build/gen-key ./

ENTRYPOINT ["./gen-key"]
CMD ["--origin=binarytransparency.log/example", "--private-key-path=/home/app/keys/private.key", "--public-key-path=/home/app/keys/public.key"]
