FROM golang:1.24.4@sha256:10c131810f80a4802c49cab0961bbe18a16f4bb2fb99ef16deaa23e4246fc817 AS build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
# cgo needed for go-sqlite3
RUN CGO_ENABLED=1 go build -v -o ./witness-add-key ./cmd/witness-add-key

FROM golang:1.24.4@sha256:10c131810f80a4802c49cab0961bbe18a16f4bb2fb99ef16deaa23e4246fc817

WORKDIR /home/app

RUN apt-get update
RUN apt-get install sqlite3

RUN mkdir witness
RUN sqlite3 -line witness/witness.db '.database'

COPY --from=build /build/witness-add-key ./

ENTRYPOINT ["./witness-add-key"]
CMD ["--database-path=/home/app/witness/witness.db", "--public-key=/home/app/keys/public.key"]
