FROM golang:1.24.5@sha256:ef5b4be1f94b36c90385abd9b6b4f201723ae28e71acacb76d00687333c17282 AS build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN CGO_ENABLED=0 go build -v -o ./witness-add-key ./cmd/witness-add-key

FROM golang:1.24.5@sha256:ef5b4be1f94b36c90385abd9b6b4f201723ae28e71acacb76d00687333c17282

WORKDIR /home/app

RUN apt-get update
RUN apt-get install sqlite3

RUN mkdir witness
RUN sqlite3 -line witness/witness.db '.database'

COPY --from=build /build/witness-add-key ./

ENTRYPOINT ["./witness-add-key"]
CMD ["--database-path=/home/app/witness/witness.db", "--public-key=/home/app/keys/public.key"]
