name: End-to-End Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  e2e-test:
    name: "Run end-to-end test with log, witness and monitor"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod

      - name: Initialize log
        run: |
          go run ./cmd/gen-key --origin=binarytransparency.log/example
      
      - name: Initialize witness
        run: |
          sqlite3 -line witness.db '.database'
          go run ./cmd/witness-add-key --database-path witness.db --public-key public.key

      - name: Run witness
        run: |
          go run ./cmd/gen-key --origin=witness.log/example --private-key-path witness-private.key --public-key-path witness-public.key
          go run ./cmd/witness-server --database-path witness.db --private-key witness-private.key --public-key witness-public.key &

      - name: Run log
        run: |
          go run ./cmd/bt-log --storage-dir=/tmp/bt-log --private-key=private.key --public-key=public.key --purl-type=pypi --witness-url="http://localhost:8081" --witness-public-key=witness-public.key &

      - name: Verify upload and output
        run: |
          curl -XPOST http://localhost:8080/add -d "{\"purl\":\"pkg:pypi/pkgname@1.2.3?checksum=sha256:5141b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be92\"}" -o bundle
          cat bundle
          cat bundle| jq -r .checkpoint | base64 -d
          index=$(cat bundle | jq -r .index)
          if [ $index -ne 0 ]; then exit 1; else true; fi

      - name: Run monitor
        run: |
          go run ./cmd/bt-log-monitor --log-url http://localhost:8080 --public-key public.key --storage-dir /tmp/monitor --once=true --purl-version-regex="1.2.3" --purl-type-regex="pypi" --purl-name-regex="pkgname" --purl-namespace-regex=".*" --json-logging 2>log-output
          cat log-output
          purl=$(cat log-output | jq -r .purl)
          if [[ "$purl" != "pkg:pypi/pkgname@1.2.3?checksum=sha256%3A5141b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be92" ]]; then exit 1; else true; fi
