name: End-to-end Witness Database Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  e2e-databse-tests:
    name: End-to-end test with ${{ matrix.db }} witness backend
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db: [sqlite, mysql, postgres]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: go.mod

    - name: Build docker images
      run: docker compose --profile admin --profile ${{ matrix.db }} build

    - name: Generate log and witness keys
      run: |
        docker compose run gen-key-log
        docker compose run gen-key-witness

    - name: Start services
      run: docker compose --profile ${{ matrix.db }} up --wait

    - name: Verify upload and checkpoint
      run: |
        curl -XPOST http://localhost:8080/add -d "{\"purl\":\"pkg:pypi/pkgname@1.2.3?checksum=sha256:5141b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be92\"}" -o bundle
        cat bundle
        cat bundle| jq -r .checkpoint | base64 -d
        index=$(cat bundle | jq -r .index)
        if [ $index -ne 0 ]; then exit 1; else true; fi

    - name: Check container logs on failure
      if: failure()
      run: docker compose --profile ${{ matrix.db }} logs

    - name: Tear down services
      if: always()
      run: docker compose --profile ${{ matrix.db }} down --volumes --remove-orphans
