name: Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: "Run unit tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - name: Go Test
        run: go test -v -race ./...
